#!/bin/bash

source_server="recovery-production-1.civpyhkigzas.us-east-1.rds.amazonaws.com"
destination_server="production.civpyhkigzas.us-east-1.rds.amazonaws.com"
new_database_prefix="remove_me_"
#file=$(cat headway.txt)

cmd="mysql -h$destination_server -sN -e \"show databases like '$new_database_prefix%';\""
datbases=`eval $cmd`
for x in ${datbases[@]}; do
    cmd="mysql -h$destination_server -e \"SET FOREIGN_KEY_CHECKS=0; drop database if exists $x;\"" 
    eval $cmd
    echo $cmd
done
