#!/bin/bash

source_server="production.civpyhkigzas.us-east-1.rds.amazonaws.com"
destination_server="production.civpyhkigzas.us-east-1.rds.amazonaws.com"
new_database_prefix="remove_me_"
file=$(cat headway.txt)

for new_database_name in $file
do
echo -e "Copying => $existing_database_name"
existing_database_name="$new_database_prefix$new_database_name"
cmd="mysql -h$destination_server -e \"drop database if exists $new_database_name; create database $new_database_name;\""
#eval $cmd 
echo $cmd
cmd="time mysqldump -h$source_server $existing_database_name | sed 's/DEFINER=[^*]*\*/\*/g' | mysql -h$destination_server $new_database_name"
#eval $cmd
echo $cmd
done