#!/usr/bin/env python3
import sys
import string
import random
import mysql.connector
from mysql.connector import Error
from configparser import ConfigParser
from pathlib import Path
import os
import funcs as f

if len(sys.argv) > 1:
    username = sys.argv[1]
else:
    print("You must supply a username: createUser username")
    sys.exit()

def run_command(connection, command):
    cursor = connection.cursor()
    try:
        cursor.execute(command)
    except Error as e:
        print(f"The error '{e}' occurred")

def get_mysql_credentials():
    home_dir = Path.home()
    conf = ".my.cnf"
    conf = os.path.join(home_dir, conf)
    config = ConfigParser()
    config.read(conf)
    mysql_user = config.get("client", "user")
    mysql_password = config.get("client", "password")
    return mysql_user, mysql_password

def create_connection(host_name, user_name, user_password, mysql_port, mysql_database):
    connection = None
    try:
        connection = mysql.connector.connect(
            host=host_name,
            user=user_name,
            passwd=user_password,
            port=mysql_port,
            database=mysql_database,
        )
        print(f"Connection to {host_name} successful")
    except Error as e:
        print(f"The error '{e}' occurred")
        sys.exit()
    return connection

mysql_host = "production.civpyhkigzas.us-east-1.rds.amazonaws.com"
new_password = "".join(random.choices(string.ascii_uppercase + string.digits, k=15))
mysql_user, mysql_password = f.get_mysql_credentials()
connection = f.create_connection(mysql_host, mysql_user, mysql_password, 3306, "mysql")

try:
    command=""
    command=f"ALTER USER '{username}'@'10.%.%.%' IDENTIFIED BY '{new_password}';"
    #print(command)
    run_command(connection, command)

except:
    print("Fail!!!!")

print("User: ", username)
print("Password: ", new_password)
print("Host : reader-bi.civpyhkigzas.us-east-1.rds.amazonaws.com")