#!/usr/bin/env python3

import funcs as f
import mysql.connector
from mysql.connector import Error
import sys
import colorama
from colorama import Fore

local_test = False

if local_test:
    mysql_host = "127.0.0.1"
    mysql_user = "lendio"
    mysql_password = "L3nd10"
    mysql_port = 9900
else:
    mysql_host = "reader-bi.civpyhkigzas.us-east-1.rds.amazonaws.com"
    # mysql_host = 'production.civpyhkigzas.us-east-1.rds.amazonaws.com'
    mysql_port = 3306
    mysql_user, mysql_password = f.get_mysql_credentials()

mysql_database = "datateam"
connection = f.create_connection(
    mysql_host, mysql_user, mysql_password, mysql_port, mysql_database
)
cursor = connection.cursor()


foreign_key_data = f.get_fk_information_for_all_tables(connection)
print(
    Fore.YELLOW
    + f"Total number of constraints found: {len(foreign_key_data)}"
    + Fore.RESET
)

for value in foreign_key_data:
    connection = f.create_connection(
        mysql_host, mysql_user, mysql_password, mysql_port, mysql_database
    )
    cursor = connection.cursor()
    count = f.get_foreign_key_data(connection, value)
    if count == None:
        continue
    print(f"{value['Constraint_Schema']}.{value['Source_Table']}.{value['Source_Column']} - {value['Constraint_Name']} : ", end="")
    if count[0][0] > 0:
        print(f"{value['Constraint_Schema']}.{value['Constraint_Name']} : ", end="")
        print(Fore.RED + f"{count[0][0]}")
        print(
            f"{value['Source_Schema']}.{value['Source_Table']}.{value['Source_Column']}(s) that don't exist in {value['Referenced_Schema']}.{value['Referenced_Table']}.{value['Referenced_Column']} :"
        )
        print(f"** ({count[0][1]})")
        print(Fore.RESET, end="")
    else:
        print(Fore.GREEN + "Good")
        print(Fore.RESET, end="")
        pass
