#!/usr/bin/env python3
import sys
import string
import random
import requests
import json
import funcs as f
import mysql.connector
from mysql.connector import Error
import colorama
from colorama import Fore

local_test = None

if len(sys.argv) > 1:
    table_name = sys.argv[1]
    # if sys.argv[2] is not None:
    # schema_name = sys.argv[2]
    try:
        schema_name = sys.argv[2]
    except IndexError:
        print(Fore.CYAN + "No Schema specified, defaulting to optimus!" + Fore.RESET)
        schema_name = "optimus"
else:
    print(
        "You must supply at least a table name: checkFKonTable table_name [schema_name]"
    )
    sys.exit()

# local_test=True

if local_test:
    mysql_host = "127.0.0.1"
    mysql_user = "lendio"
    mysql_password = "L3nd10"
    mysql_port = 9900
else:
    mysql_host = "reader-bi.civpyhkigzas.us-east-1.rds.amazonaws.com"
    # mysql_host = 'production.civpyhkigzas.us-east-1.rds.amazonaws.com'
    mysql_port = 3306
    mysql_user, mysql_password = f.get_mysql_credentials()

mysql_database = "datateam"
connection = f.create_connection(
    mysql_host, mysql_user, mysql_password, mysql_port, mysql_database
)
cursor = connection.cursor()

f.show_table_information(connection, schema_name, table_name)

foreign_key_data = f.get_fk_information(connection, schema_name, table_name)

print(
    Fore.YELLOW
    + f"Total number of constraints in {schema_name}.{table_name}: {len(foreign_key_data)}"
    + Fore.RESET
)

for value in foreign_key_data:
    get_orphaned_count = f"select count(1) as orphaned_values,group_concat(DISTINCT a.{value['Source_Column']} ORDER BY a.{value['Source_Column']} ) from {value['Source_Schema']}.{value['Source_Table']} a \
		left join {value['Referenced_Schema']}.{value['Referenced_Table']} b on a.{value['Source_Column']} = b.{value['Referenced_Column']} \
		where a.{value['Source_Column']} is NOT NULL \
		and b.{value['Referenced_Column']} is NULL;"
    try:
        cursor.execute(get_orphaned_count)
        count = cursor.fetchall()
    except mysql.connector.ProgrammingError as err:
        print(
            Fore.RED
            + f"An error occured checking for FK orphans -> {err.msg}"
            + Fore.RESET
        )
        continue
    except mysql.connector.Error as err:
        print(err)
    print(f"{value['Constraint_Schema']}.{value['Constraint_Name']} : ", end="")
    if count[0][0] > 0:
        print(Fore.RED + f"{count[0][0]}")
        print(
            f"{value['Source_Schema']}.{value['Source_Table']}.{value['Source_Column']}(s) that don't exist in {value['Referenced_Schema']}.{value['Referenced_Table']}.{value['Referenced_Column']} :"
        )
        print(f"** ({count[0][1]})")
        print(Fore.RESET, end="")
    else:
        print(Fore.GREEN + "Good")
        print(Fore.RESET, end="")
