#!/bin/bash
if [ -z ${3} ]; then
        echo -e "\e[1m\e[36m"
        echo "Usage:"
        echo ""
        echo "copydbuser <username> <role> <destination>"
        echo ""
        echo "<username> You can use finddbuser to get the username you need"
        echo "<role> [superAdmin, admin,developer]"
        echo "<destination> You can use dbs to find the server name to copy the user to."
        echo ""
fi

source_server='production.civpyhkigzas.us-east-1.rds.amazonaws.com'
source_port=3306

sql=`pt-show-grants -hproduction.civpyhkigzas.us-east-1.rds.amazonaws.com | grep $1 | head -n3 `

if [ ${2} == 'superAdmin' ]; then
    sql="$sql GRANT \`rds_superuser_role\`@\`%\` TO \`${1}\`@\`10.%.%.%\`;"
elif [ ${2} == 'admin' ]; then
    sql="$sql GRANT \`admin\`@\`%\`,\`developer\`@\`%\` TO \`${1}\`@\`10.%.%.%\`;"
elif [ ${2} == 'developer' ]; then
    sql="$sql GRANT \`developer\`@\`%\` TO \`${1}\`@\`10.%.%.%\`;"
else
    echo "Invalid <role> must be developer or admin"
fi
sql="$sql SET DEFAULT ROLE ALL TO \`${1}\`@\`10.%.%.%\`;"

echo $sql

mysql -h $3 -e "$sql"


