#!/usr/bin/env python3
import sys
import string
import random
import mysql.connector
from mysql.connector import Error
from configparser import ConfigParser
from pathlib import Path
import os
import funcs as f

mysql_port = 3306
mysql_database = 'mysql'

# These variables must be set before running:
host_name = 'server.aws.com'
admin_user = 'root'
admin_password = 'xxxyyyzzz'
new_database_name = 'NEW_DATABASE'
new_user = new_database_name
new_worker = "".join(new_user + "_worker")
new_user_password = "".join(random.choices(string.ascii_uppercase + string.digits, k=15))
new_worker_password = "".join(random.choices(string.ascii_uppercase + string.digits, k=15))

def run_command(connection, command):
    cursor = connection.cursor()
    try:
        cursor.execute(command)
    except Error as e:
        print(f"The error '{e}' occurred")

try:
    with open("config/.createNewServer.sql", "r") as file_object:
        command = ""
        for line in file_object:
            command = line.replace("DATABASE_NAME", new_database_name)
            command = command.replace("USER1", new_user)
            command = command.replace("USER2", new_worker)
            command = command.replace("PASSWORD1", new_user_password)
            command = command.replace("PASSWORD2", new_worker_password)
            print(command, end ="")
            #run_command(connection, command)

except:
    if file_object.closed == False:
        print("File is not closed")
    else:
        print("File is closed")

print("Server: ", host_name)
print("New Database: ", new_database_name)
print("New User: ", new_user)
print("Password: ", new_user_password)
print("New Worker: ", new_worker)
print("New Worker Password: ", new_worker_password)