#!/bin/bash
server='production.civpyhkigzas.us-east-1.rds.amazonaws.com'
port=3306
echo -e "\e[1m\e[36m"

count=1
if [ -z ${1} ]; then
        echo -e "\e[1m\e[31m"
        echo "You must enter a portion of a user to search for..."
fi

mysql  --protocol=tcp  --host=$server -P $port -e "select user,host,plugin from mysql.user where user like '%"$1"%'"