#!/bin/bash
# Deletes Circle Test Cluster and Instance
cluster=circle-recovery-cluster
instance=circle-recovery-instance
echo "Deleting Instance $instance..."
aws rds delete-db-instance --db-instance-identifier $instance --skip-final-snapshot > /dev/null
result=1
until [ $result == 0 ]; do
    echo -e "\r\033[1A\033[0KStill deleting instance... $i"
    sleep 60
    result=`aws rds describe-db-instances --output text | grep -c $instance`
    echo $result
    i=$((i+1))
done
echo "Deleting Cluster $cluster..."
result=1
i=1
aws rds delete-db-cluster --db-cluster-identifier $cluster --skip-final-snapshot > /dev/null
until [ $result == 0 ]; do
    echo -e "\r\033[1A\033[0KStill deleting cluster... $i"
    sleep 60
    result=`aws rds describe-db-clusters --output text | grep -c $cluster`
    echo $result
    i=$((i+1))
done
printf "%b\n" "\033[96mCluster $cluster Deleted!!!"

# aws rds describe-db-clusters --output text | grep -c circle-recovery-cluster
#aws rds delete-db-cluster --db-cluster-identifier circle-recovery-cluster --skip-final-snapshot