#!/usr/bin/env python3
import boto3
import sys
region = 'us-east-1'
instances = ['i-07fb94d90755f098b']
ec2 = boto3.client('ec2', region_name=region)
if len(sys.argv) > 1:
    if  sys.argv[1] == "stop":
        try:
            ec2.stop_instances(InstanceIds=instances)
        except:
            print("An error occured")
            sys.exit()
        print("Stopping Instance...")
    else:
        try:
            ec2.start_instances(InstanceIds=instances)
        except:
            print("An error ocurred")
            sys.exit()
        print("Starting Instance ...")
else:
    print(
        "You must specify either start or stop as the action"
    )
    sys.exit()

#ec2.stop_instances(InstanceIds=instances)
