#!/usr/bin/env python3
import sys
import string
import random
import requests
import json
import funcs as f

mysql_host = 'production.civpyhkigzas.us-east-1.rds.amazonaws.com'
mysql_user,mysql_password = f.get_mysql_credentials()
fetch_user_query = "select distinct(user) from mysql.user order by user" 
connection = f.create_connection(mysql_host, mysql_user, mysql_password)
cursor = connection.cursor()

cursor.execute(fetch_user_query)
# get all records
records = cursor.fetchall()
print("Total number of users in MySQL: ", cursor.rowcount)
file1 = open("config/.validUsers.txt", "r")
readfile = file1.read()
users = []
for row in records:
    if row[0] not in readfile: 
        #print(row[0])
        users.append(row[0])
print(f"There are {len(users)} unknown users")

if len(users) > 0:
    if "notify" in sys.argv:
            send_slack_notification(users)
    else :
        print(users)
