#!/usr/bin/env python3
from datetime import datetime, timedelta
import pytz
import sys

local_time = pytz.timezone("America/Denver")


def fix_timestamp_format(tz):
    tz = str(tz).replace(" ", "T")
    tz = str(tz).replace("+00:00", "")
    return tz


try:
    if sys.argv[1] == "r":
        now = datetime.now() - timedelta(hours=1)
    else:
        time = sys.argv[1]
except IndexError:
    now = datetime.now()
    # now = datetime.now() - timedelta(hours=1)
    time = now.strftime("%Y-%m-%d %H:%M:%S")

time = now.strftime("%Y-%m-%d %H:%M:%S")
naive_datetime = datetime.strptime(str(time), "%Y-%m-%d %H:%M:%S")

local_datetime = local_time.localize(naive_datetime, is_dst=None)

utc_datetime = local_datetime.astimezone(pytz.utc)

print(fix_timestamp_format(utc_datetime))
