create table partnerCommissions2(
   	id int unsigned not null,
	recordType varchar(30) default NULL,
	userName varchar(250) default NULL,
	payoutAmount  decimal(12,3) default NULL,
	statementPeriodStartDate timestamp NULL default NULL,
	revenue decimal(12,3) DEFAULT NULL,
	payoutRuleName varchar(50) DEFAULT NULL,
	planName varchar(30) DEFAULT NULL,
	userExternalId varchar(30) DEFAULT NULL,
	borrowerId int(10) unsigned DEFAULT NULL,
	`name` varchar(250) DEFAULT NULL,
	currentBorrowerStatus varchar(30) DEFAULT NULL,
	stage  varchar(30) DEFAULT NULL,
	mineralGroup varchar(30) DEFAULT NULL,
	phone varchar(30) DEFAULT NULL,
	street  varchar(200) DEFAULT NULL,
	street2  varchar(200) DEFAULT NULL,
	city  varchar(100) DEFAULT NULL,
	`state`  varchar(3) DEFAULT NULL,
	zip varchar(13) DEFAULT NULL,
	dateClosed timestamp NULL default NULL,
	fundedAmount  decimal(15,3) DEFAULT NULL,
	acceptedOfferId int unsigned DEFAULT NULL,
	`type`  varchar(30) DEFAULT NULL,
	loanProductCategoryType varchar(30) DEFAULT NULL,
	loanProductLenderId int unsigned DEFAULT NULL,
	points  decimal(8,3) DEFAULT NULL,
	housePoints  decimal(8,3) DEFAULT NULL,
	buyRate  varchar(30) DEFAULT NULL,
	paymentFrequency varchar(30) DEFAULT NULL,
	paymentAmount decimal(12,3) DEFAULT NULL,
	factor decimal(5,3) DEFAULT NULL,
	term smallint DEFAULT NULL,
	numPayments smallint DEFAULT NULL,
	interestRate decimal(8,3) DEFAULT NULL,
	offerReceivedAt timestamp NULL default NULL,
	offerAcceptedAt timestamp NULL default NULL,
	opportunityId int unsigned DEFAULT NULL,
	oppStart timestamp NULL default NULL,
	oppEnd timestamp NULL default NULL,
	disposition  varchar(30) DEFAULT NULL,
	appCompletedAt timestamp NULL default NULL,
	appSent  timestamp NULL default NULL,
	docPrep timestamp NULL default NULL,
	marketingId int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
